services:
  - type: web
    name: housely-api
    env: python
    plan: free
    buildCommand: pip install --no-cache-dir --prefer-binary -r requirements.txt
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=$PORT
